steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'botFunction', '--trigger-http', '--runtime', 'nodejs14', '--allow-unauthenticated']